on:
  push:
    branches:
    - feat/ci
  workflow_dispatch:
    inputs:
      base_image:
        type: string
        required: false
        description: Base image to use for devcontainer
      nim_version:
        type: string
        required: false
        description: The version of Nim to be installed

env:
  DEFAULT_BASE_IMAGE: mcr.microsoft.com/devcontainers/base:noble
  DEFAULT_NIM_VERSION: 2.2.6

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
    - name: Init script
      id: init
      run: |
        base_image="${{ inputs.base_image || env.DEFAULT_BASE_IMAGE }}"
        nim_version="${{ inputs.nim_version || env.DEFAULT_NIM_VERSION }}"
        base_tag=$(echo $base_image | cut -d ':' -f2)
        if [[ -z "$base_tag" ]]; then
          echo "Can't get base image tag" >&2
          exit 1
        fi
        echo "base_image=$base_image"                                      >> $GITHUB_OUTPUT
        echo "nim_version=$nim_version"                                    >> $GITHUB_OUTPUT
        echo "tag=ghcr.io/${{ github.repository }}:$nim_version-$base_tag" >> $GITHUB_OUTPUT 
    - name: Checkout
      uses: actions/checkout@v6
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.init.outputs.tag }}
        build-args: |
          BASE_IMAGE=${{ steps.init.outputs.base_image }}
          NIM_VERSION=${{ steps.init.outputs.nim_version }}
      